# # """
# # Django settings for server project.

# # Generated by 'django-admin startproject' using Django 6.0.2.

# # For more information on this file, see
# # https://docs.djangoproject.com/en/6.0/topics/settings/

# # For the full list of settings and their values, see
# # https://docs.djangoproject.com/en/6.0/ref/settings/
# # """

# # from pathlib import Path

# # # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent


# # # Quick-start development settings - unsuitable for production
# # # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # # SECURITY WARNING: keep the secret key used in production secret!
# # SECRET_KEY = 'django-insecure-c6+e5i_h_*mifz_q*0^&u6a()%gxmki8(3wu_k^$^!lg#m(ywl'

# # # SECURITY WARNING: don't run with debug turned on in production!
# # DEBUG = True

# # ALLOWED_HOSTS = []


# # # Application definition

# # INSTALLED_APPS = [
# #     'django.contrib.admin',
# #     'django.contrib.auth',
# #     'django.contrib.contenttypes',
# #     'django.contrib.sessions',
# #     'django.contrib.messages',
# #     'django.contrib.staticfiles',


# #     'rest_framework',
# # 'rest_framework.authtoken',

# #     # Local apps
# #     'analytics',
# # ]


# # MIDDLEWARE = [
# #     'corsheaders.middleware.CorsMiddleware',   # must be near top
# #     'django.middleware.security.SecurityMiddleware',
# #     'django.contrib.sessions.middleware.SessionMiddleware',
# #     'django.middleware.common.CommonMiddleware',
# #     'django.middleware.csrf.CsrfViewMiddleware',
# #     'django.contrib.auth.middleware.AuthenticationMiddleware',
# #     'django.contrib.messages.middleware.MessageMiddleware',
# #     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# # ]


# # ROOT_URLCONF = 'server.urls'

# # TEMPLATES = [
# #     {
# #         'BACKEND': 'django.template.backends.django.DjangoTemplates',
# #         'DIRS': [],
# #         'APP_DIRS': True,
# #         'OPTIONS': {
# #             'context_processors': [
# #                 'django.template.context_processors.request',
# #                 'django.contrib.auth.context_processors.auth',
# #                 'django.contrib.messages.context_processors.messages',
# #             ],
# #         },
# #     },
# # ]

# # WSGI_APPLICATION = 'server.wsgi.application'


# # # Database
# # # https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# # DATABASES = {
# #     'default': {
# #         'ENGINE': 'django.db.backends.sqlite3',
# #         'NAME': BASE_DIR / 'db.sqlite3',
# #     }
# # }


# # # Password validation
# # # https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# # AUTH_PASSWORD_VALIDATORS = [
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
# #     },
# #     {
# #         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
# #     },
# # ]




# # REST_FRAMEWORK = {
# #     "DEFAULT_AUTHENTICATION_CLASSES": [
# #         "rest_framework.authentication.TokenAuthentication",
# #     ],
# #     "DEFAULT_PERMISSION_CLASSES": [
# #         "rest_framework.permissions.IsAuthenticated",
# #     ],
# # }



# # # Internationalization
# # # https://docs.djangoproject.com/en/6.0/topics/i18n/

# # LANGUAGE_CODE = 'en-us'

# # TIME_ZONE = 'UTC'

# # USE_I18N = True

# # USE_TZ = True

# # CORS_ALLOW_ALL_ORIGINS = True



# # # Static files (CSS, JavaScript, Images)
# # # https://docs.djangoproject.com/en/6.0/howto/static-files/

# # STATIC_URL = 'static/'


# """
# Django settings for server project.
# Supports:
# - Web frontend (React / Browser)
# - Desktop frontend (PyQt)
# - Single REST API backend
# """

# from pathlib import Path
# import os

# # --------------------------------------------------
# # Base directory
# # --------------------------------------------------
# BASE_DIR = Path(__file__).resolve().parent.parent


# # --------------------------------------------------
# # Security
# # --------------------------------------------------
# SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-dev-secret")

# DEBUG = os.environ.get("DEBUG", "True") == "True"

# # FIX: allow render + local without breaking anything
# ALLOWED_HOSTS = ["localhost", "127.0.0.1", "chemical-equipment-parameter-visualizer-uer9.onrender.com"]


# # --------------------------------------------------
# # Applications
# # --------------------------------------------------
# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',

#     'rest_framework',
#     'rest_framework.authtoken',
#     'corsheaders',

#     'analytics',
# ]


# # --------------------------------------------------
# # Middleware
# # --------------------------------------------------
# MIDDLEWARE = [
#     'corsheaders.middleware.CorsMiddleware',
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',

#     # KEEP CSRF (your API auth already handles this correctly)
#     'django.middleware.csrf.CsrfViewMiddleware',

#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
# ]


# # --------------------------------------------------
# # URL / WSGI
# # --------------------------------------------------
# ROOT_URLCONF = 'server.urls'

# WSGI_APPLICATION = 'server.wsgi.application'


# # --------------------------------------------------
# # Templates (FIXES admin.E403 — THIS WAS THE ERROR)
# # --------------------------------------------------
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / "templates"],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]


# # --------------------------------------------------
# # Database
# # --------------------------------------------------
# DATABASES = {
#     'default': {
#         'ENGINE': os.environ.get(
#             "DB_ENGINE",
#             "django.db.backends.sqlite3"
#         ),
#         'NAME': os.environ.get(
#             "DB_NAME",
#             BASE_DIR / "db.sqlite3"
#         ),
#     }
# }


# # --------------------------------------------------
# # Password validation
# # --------------------------------------------------
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
# ]


# # --------------------------------------------------
# # Django REST Framework
# # (UNCHANGED — your views already override permissions)
# # --------------------------------------------------
# REST_FRAMEWORK = {
#     "DEFAULT_AUTHENTICATION_CLASSES": [
#         "rest_framework.authentication.TokenAuthentication",
#     ],
#     "DEFAULT_PERMISSION_CLASSES": [
#         "rest_framework.permissions.IsAuthenticated",
#     ],
# }


# # --------------------------------------------------
# # CORS (UNCHANGED)
# # --------------------------------------------------
# CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOW_HEADERS = [
#     'authorization',
#     'content-type',
#     'accept',
#     'origin',
#     'user-agent',
# ]


# # --------------------------------------------------
# # Internationalization
# # --------------------------------------------------
# LANGUAGE_CODE = 'en-us'
# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True


# # --------------------------------------------------
# # Static files
# # --------------------------------------------------
# STATIC_URL = '/static/'
# STATIC_ROOT = BASE_DIR / 'staticfiles'


# # --------------------------------------------------
# # Default primary key field type
# # --------------------------------------------------
# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


from pathlib import Path
import os

# --------------------------------------------------
# Base directory
# --------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------
# Security
# --------------------------------------------------
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "unsafe-dev-secret")

DEBUG = os.environ.get("DEBUG", "True") == "True"

# FIX: allow render + local without breaking anything
ALLOWED_HOSTS = ["localhost", "127.0.0.1", "chemical-equipment-parameter-visualizer-uer9.onrender.com"]


# --------------------------------------------------
# Applications
# --------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    'analytics',
]


# --------------------------------------------------
# Middleware
# --------------------------------------------------
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    # KEEP CSRF (your API auth already handles this correctly)
    'django.middleware.csrf.CsrfViewMiddleware',

    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


# --------------------------------------------------
# URL / WSGI
# --------------------------------------------------
ROOT_URLCONF = 'server.urls'

WSGI_APPLICATION = 'server.wsgi.application'


# --------------------------------------------------
# Templates (FIXES admin.E403 — THIS WAS THE ERROR)
# --------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


# --------------------------------------------------
# Database
# --------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': os.environ.get(
            "DB_ENGINE",
            "django.db.backends.sqlite3"
        ),
        'NAME': os.environ.get(
            "DB_NAME",
            BASE_DIR / "db.sqlite3"
        ),
    }
}


# --------------------------------------------------
# Password validation
# --------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# --------------------------------------------------
# Django REST Framework
# (UNCHANGED — your views already override permissions)
# --------------------------------------------------
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}


# --------------------------------------------------
# CORS (UNCHANGED)
# --------------------------------------------------
CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'accept',
    'origin',
    'user-agent',
]


# --------------------------------------------------
# Internationalization
# --------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# --------------------------------------------------
# Static files
# --------------------------------------------------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'


# --------------------------------------------------
# Default primary key field type
# --------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

